### ISSUE TITLE
how do I 'install' your saltpad states to my salt-master install?

### ISSUE THREAD

**Issue by TheBigBear** [irtnog/salt-states#4]
Sorry, this is a bit of a newbie question. I would really like to have 'saltpad' running as I start exploring salt. 
But I don't have a 'rpm' for chausette for my centos 6.x, so I thought I wanted to go the apache + mod_wsgi route.

Could that work? 

And is that what your 'saltpad-states' use?

Could you help me with a few simple step by step instructions, on how I take your saltpad-states, where I put them on my salt master, and how I start the whole thing installing, configuring itself and starting it all up? 

in my scenario my salt-master and the saltpad app would all be on the same centos 6.x server.

**Comment by xenophonf** [comment]
I documented my example saltpad configuration in [saltpad/pillar.example](https://github.com/irtnog/salt-states/blob/production/saltpad/pillar.example).  If you want to see it in context, take a look at my [example Salt master configuration](https://github.com/irtnog/salt-pillar-example/blob/master/salt/example/com/init.sls).  Note that my configuration uses my [Apache state formula](https://github.com/irtnog/salt-states/tree/production/apache), not the one from [saltstack-formulas/apache-formula](https://github.com/saltstack-formulas/apache-formula).  I do use mod_wsgi together with saltpad's requisites (flask, etc.).  As you can see from the configuration examples, I also run the rest_cherrypy version of salt-api, which saltpad uses to access the master.  I strongly recommend against exposing salt-api to the public Internet.  I'm working on a configuration that uses mod_wsgi to host a publicly accessible version of salt-api suitable for use by things like GitHub webhooks, with [ModSecurity](https://www.modsecurity.org/) (a WAF/IDS/IPS) and a [proper TLS configuration](https://wiki.mozilla.org/Security/Server_Side_TLS) protecting it.

**Comment by xenophonf** [comment]
Installing my saltpad states should be a simple matter of copying that folder from my production branch into your state tree, e.g., `/srv/salt/states` and configuring it via Pillar.  Likewise, you should install and configure both [saltstack-formulas/apache-formula](https://github.com/saltstack-formulas/apache-formula) and [saltstack-formulas/salt-formula](https://github.com/saltstack-formulas/salt-formula), the former to help you deploy a suitable mod_wsgi configuration and the latter to help you deploy salt-api.  As I said, I don't use apache-formula, but you should be able to figure it out given my configs.  Feel free to open a new issue or reach out to me via email/IRC if you need more help.  I'm sometimes on the [#salt IRC channel](http://webchat.freenode.net/?channels=salt) under this nick.  My email address is on my GitHub profile.
